apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dmz-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.40.50-192.168.40.99
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dmz-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - dmz-ip-pool