apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: festivalstream-root-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/Timkoops/festivalstream'
    targetRevision: HEAD
    path: infrastructure
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  syncOptions:
    - CreateNamespace=true