apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-streaming-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:          
          requests:
            cpu: "100m"      # 100 millicores (0.1 CPU) gereserveerd
            memory: "128Mi"
          limits:
            cpu: "500m"      # Maximaal een halve CPU per pod
            memory: "256Mi"