apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              - 'alertmanager:9093'

    rule_files:
      - '/etc/prometheus/alerts.yml'

    scrape_configs:
      - job_name: 'servers'
        static_configs:
          - targets: 
            - 'master01:9100'
            - 'worker01:9100'
            - 'worker02:9100'

  alerts.yml: |
    groups:
      - name: test-alerts
        rules:
          - alert: TestEmailAlert
            expr: vector(1)
            for: 1m