[masters]
master01 ansible_host=192.168.20.0  # Master ip

[new_workers]
worker03 ansible_host=192.168.20.3  # Het IP in van de nieuwe worker

[all:vars]
ansible_user=student                # De gebruiker waarmee Ansible inlogt via SSH