apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chat-pvc
  namespace: storage-chat
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi