apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: storage-logs
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi