apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-pvc
  namespace: storage-monitoring
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi