apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-storage-pvc
  namespace: monitoring
spec:
  storageClassName: truenas-nfs 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi 