apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stream-pvc
  namespace: storage-streaming
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi