apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
  namespace: storage-web
spec:
  storageClassName: truenas-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi