apiVersion: v1
kind: Namespace
metadata:
  name: vod
---
apiVersion: v1
kind: Namespace
metadata:
  name: chat
---
apiVersion: v1
kind: Namespace
metadata:
  name: streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: web-client
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-vod
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-chat
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-streaming
---
apiVersion: v1
kind: Namespace
metadata:
  name: democratic-csi-truenas
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-web
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-logs
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: dashboard